### ISSUE TITLE
Route name 

### ISSUE THREAD

**Issue by gamevnlc** [igaster/laravel_cities#12]
Hi, your package is great. I am using HTTP API and I want to define route name for each request . Is there any way to do it. I could override your `method` but I looking for some short way to do

**Comment by igaster** [comment]
Hi @gamevnlc , do you need to overwrite the [API routes](https://github.com/igaster/laravel_cities/blob/master/src/routes.php)? You can siply copy these from the source file and define yours. You don't need to include my routes if you don't want to use them!

**Comment by gamevnlc** [comment]
@igaster 
Thank you.  I have made my own route
