### ISSUE TITLE
Need option to disable automatic create geo migration

### ISSUE THREAD

**Issue by gamevnlc** [igaster/laravel_cities#13]
I want to to custom `geo` table and I don't want to add your define `geo` migration.  It's always error when i tried to run `migrate reset` . Could you add option to disable migration or just change add check if table exist at `down` method in your mgration

**Comment by igaster** [comment]
You can "cheat" by creating your own migration with the same filename "2017_02_13_090952_geo.php" and leave it empty. This will trick laravel to believe that it is the same migration and will not execute the one from the package...

I don't know if laravel can skip package migrations... This could be a useful feature...
