### ISSUE TITLE
nothing to migrate

### ISSUE THREAD

**Issue by heenaI** [igaster/laravel_cities#2]
I am trying to install this package on my server after installing everything when I try to migrate with php artisan migrate it tells me there is nothing to migrate. Also the migration table is not there. here is what I did 

`php composer.phar require igaster/laravel_cities`

```
change in providers
Igaster\LaravelCities\GeoServiceProvider::class,

Ran this script
mkdir storage/geo
cd storage/geo
wget http://download.geonames.org/export/dump/allCountries.zip && unzip allCountries.zip && rm allCountries.zip
wget http://download.geonames.org/export/dump/hierarchy.zip && unzip hierarchy.zip && rm hierarchy.zip
```

now when I run` php artisan migrate` it tells me there is nothing to migrate

**Comment by igaster** [comment]
Hello!

The migration is registered at GeoServiceProvider which should be inserted inside the 

        /*
         * Package Service Providers...
         */

area of app[] array....

What exactly is your Laravel version?

**Comment by heenaI** [comment]
Hi, 
Do you mean in the app.php file? I have inserted Igaster\LaravelCities\GeoServiceProvider::class,  in the app.php file in config folder under providers under 
    /*
     * Package Service Providers...
     */ 

below  Laravel\Tinker\TinkerServiceProvider::class,

But I have inserted it in the 'providers' => [] array, as mentioned in the documentation shold I enter it somewhere else?

**Comment by heenaI** [comment]
My Laravel version is 5.4

**Comment by heenaI** [comment]
If I do the migration manually by copying the migration file vendor/igaster/laravel_cities/src/migrations to database/migrations would this be a solution?

**Comment by heenaI** [comment]
it worked !! after php artisan cache:clear

**Comment by igaster** [comment]
Strange behaviour... I don't know what caused it... 
BTW copying the migration file would be a valid work around...

I'm glad it works now!
