### ISSUE TITLE
artisan geo:seed is stop at 60% with no error

### ISSUE THREAD

**Issue by sameervirus** [igaster/laravel_cities#26]
When setup at geo:seed is stop at 60% with no error just courser return. i'm do this at shard hosting

**Comment by igaster** [comment]
Hello @sameervirus, 

A) Maybe this is a memory issue. You can update to the latest version of the pakage and use the `--chunk` option when you import your data. ie:

`php artisan geo:seed --chunk=3000`

Try with smaller chunk sizes. 

B) Also it is possible that your hosting provider will not allow any process to run for too long! Maybe it will just timeout
