### ISSUE TITLE
Not found some cities

### ISSUE THREAD

**Issue by sorbing** [igaster/laravel_cities#3]
Not all cities import to the database table `geo`. I'm not found city "Korsun'-Shevchenkivs'kyy".
```
Geo::search("Korsun'-Shevchenkivs'kyy")->count(); // 0
```
SQL query returns also emty result:
```
SELECT * FROM `geo` WHERE country = 'UA' and name LIKE 'Korsun%'
```
But geonames knows this city: http://www.geonames.org/search.html?q=Korsun&country=UA
Hierarchy tree: http://geotree.geonames.org/704858/
In what can be problem? Thanks.

**Comment by sorbing** [comment]
I refresh the migration with seed, and see console output:
```
Finished: 193 Countries imported.  18555 orphan items skiped
Truncating 'geo' table...
Writing in Database
100/100 [============================] 100% Done
Timing: 1210.1798610687 sec
```
It's a normaly? > **18555 orphan items skiped**

**Comment by igaster** [comment]
Hello @Sorbing, this is a normal behavior. This package will import only the items with the following feature codes:

- PCLI: a Country
- PPLC: a Capital
- ADM1: a primary administrative division of a country, such as a state in the United States
- ADM2: a subdivision of a first-order administrative division
- ADM3: a subdivision of a second-order administrative division

Other items are consindered "smaller" areas and are skipped.

If you search the UA.txt (which containts only the Ukranian items) for `Korsun'-Shevchenkivs'kyy` you will see that it has a feature code of `PPLA2` so it is skipped.

For a list of all availavle feature codes see: [geo-names feature codes](http://www.geonames.org/export/codes.htmll)

As an alternative you can provide your [custom seeding files](https://github.com/igaster/laravel_cities#seed-with-custom-data), for example:
```
[
  {
    "name": "Korsun’-Shevchenkivs’kyy",
    "parent_id":  710802,
    "alternames": ["Korsun"],
    "lat": "49.41894",
    "long": "31.25865"
  }
]
```
Geonames will help you find all information. For example if you locate [Korsun](http://www.geonames.org/maps/google_49.419_31.259.html) and click on the "hierarcy" icon you will find it's parent id, corrdinates etc...

I hope these will help you...

**Comment by sorbing** [comment]
Hello, @igaster. Many thanks! You helped me a lot)
Can you tell me please - Is there a way to set the import depth of the items via config?
As example `configs/geo.php`:
```
'import_depth_level': 'PPLA2'
```
I could make PR with this features.. Thanks!

**Comment by ftrudeau** [comment]
I concur. But it simply could be an array of feature codes to import.

**Comment by igaster** [comment]
Unfortunatelly this limit is hardcoded... But since this is a common requirement I will try to find some time to provide such an option to the import script.

The original plan was to support all entities with at least the size of a city. I understand that in some countries some cities have been filtered out because they have a higher depth than `ADM3`, so this is something I will need to reavaluate. Thank you for your feedback

**Comment by Nuranto** [comment]
+1, no city at all for some countries. (FR for example)
