### ISSUE TITLE
conflicts with your root composer.json require (^9.21)

### ISSUE THREAD

**Issue by webadminisob** [igaster/laravel_cities#39]
igaster/laravel_cities v1.3.11 requires laravel/framework 5.*|^6.0|7.*|8.* -> found laravel/framework[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.21)

**Comment by igaster** [comment]
Thanks! It's safe to white-list all laravel versions. Fixed here: https://github.com/igaster/laravel_cities/releases/tag/v1.3.12
