### ISSUE TITLE
Not seeding

### ISSUE THREAD

**Issue by zarpio** [igaster/laravel_cities#8]
Using Laravel 5.4.36

Installed as follows

`composer require igaster/laravel_cities`

**Added** 
```
'providers' => [
    //...
    Igaster\LaravelCities\GeoServiceProvider::class,
];

```
**Created** 
folder -> storage\geo for placed both files "hieararcy.txt" & "allCountries.txt".

`php artisan migrate `
(table created successfully)

`php artisan geo:seed` 

39/100 [==========>-----------------]  39%
and stopped command ... nothing happen, no data in the table.

**Comment by igaster** [comment]
It will first try to build a tree in the memory and then it will write it
to the database...

Since it doesn't seem to be a timeout issue, I suspect that PHP run out of
memory...

Can you check the maximum memory setting of PHP? Are you using a VM server
with limited resources?

**Comment by zarpio** [comment]
Yes, you were right, php.ini was having following values

`memory_limit = 128M`
increased to **512M** and it worked

`SELECT COUNT(*) FROM geo `
(170799) records were seeded.

**Comment by igaster** [comment]
Thank you for verifying that it worked...

I had to trade performance vs memory usage and as a result it requires too
much memory... You can imagine how \would be required when you import ~1GB
of data from that file...

Thanks to you now we have a metric: 128MB < php_memory < 512MB :-)
